import 'dart:math' as math;
import 'dart:typed_data';

import 'package:vector_math/vector_math.dart';

import 'circuit.dart';

/// A heightfield over a rectangle of the scene, rows running south to north.
class TerrainGrid {
  TerrainGrid({
    required this.size,
    required this.minX,
    required this.maxX,
    required this.southZ,
    required this.northZ,
    required this.heights,
    this.sea,
  });

  /// Nodes per side.
  final int size;
  final double minX;
  final double maxX;

  /// Scene z of the southern edge (rows start here) and the northern one.
  /// North is -Z, so [southZ] > [northZ].
  final double southZ;
  final double northZ;

  /// Row-major scene heights, `size * size`.
  final Float64List heights;

  /// Row-major flags for nodes under the sea, when known.
  final Uint8List? sea;

  /// Whether the node nearest scene ([x], [z]) is under the sea.
  bool isSea(double x, double z) {
    final sea = this.sea;
    if (sea == null) return false;
    final c = ((x - minX) / (maxX - minX) * (size - 1)).round().clamp(
      0,
      size - 1,
    );
    final r = ((z - southZ) / (northZ - southZ) * (size - 1)).round().clamp(
      0,
      size - 1,
    );
    return sea[r * size + c] != 0;
  }

  double nodeX(int column) => minX + (maxX - minX) * column / (size - 1);
  double nodeZ(int row) => southZ + (northZ - southZ) * row / (size - 1);
  double node(int row, int column) =>
      heights[row.clamp(0, size - 1) * size + column.clamp(0, size - 1)];

  /// Bilinear height at scene ([x], [z]), clamped to the grid's edges.
  double heightAt(double x, double z) {
    final fx = ((x - minX) / (maxX - minX)).clamp(0.0, 1.0) * (size - 1);
    final fy = ((z - southZ) / (northZ - southZ)).clamp(0.0, 1.0) * (size - 1);
    final c = math.min(size - 2, fx.floor()),
        r = math.min(size - 2, fy.floor());
    final tx = fx - c, ty = fy - r;
    final top = node(r, c) + (node(r, c + 1) - node(r, c)) * tx;
    final bottom = node(r + 1, c) + (node(r + 1, c + 1) - node(r + 1, c)) * tx;
    return top + (bottom - top) * ty;
  }
}

/// A polygon or line in the scene's horizontal plane, with its OSM tag.
class EnvironmentShape {
  const EnvironmentShape(this.kind, this.points, {this.height = 0});

  /// Land use ("grass", "wood"…), road class ("service", "tertiary"…), or
  /// water kind.
  final String kind;

  /// Scene (x, z) points.
  final List<Vector2> points;

  /// Building height in meters.
  final double height;
}

/// What surrounds a circuit: terrain, water, land use, roads and buildings
/// from OpenStreetMap, as generated by F1TrackViewer, in scene space.
class CircuitEnvironment {
  CircuitEnvironment({
    required this.terrain,
    required this.water,
    required this.landuse,
    required this.roads,
    required this.buildings,
  });

  /// Parses the environment documents of [circuit].
  ///
  /// Heights become scene heights by subtracting the circuit's mean
  /// elevation, so terrain and track share one datum.
  factory CircuitEnvironment.fromJson({
    required Circuit circuit,
    required Map<String, dynamic> manifest,
    required Map<String, dynamic> terrain,
    Map<String, dynamic>? surface,
    required Map<String, dynamic> water,
    required Map<String, dynamic> landuse,
    required Map<String, dynamic> roads,
    required Map<String, dynamic> buildings,
  }) {
    final projection = circuit.projection;
    List<Vector2> points(Object? raw) => [
      for (final p in (raw as List? ?? const []).cast<List>())
        () {
          final v = projection.project(
            (p[0] as num).toDouble(),
            (p[1] as num).toDouble(),
          );
          return Vector2(v.x, v.z);
        }(),
    ];

    final bbox = manifest['bbox'] as Map<String, dynamic>;
    final sw = projection.project(
      (bbox['minLon'] as num).toDouble(),
      (bbox['minLat'] as num).toDouble(),
    );
    final ne = projection.project(
      (bbox['maxLon'] as num).toDouble(),
      (bbox['maxLat'] as num).toDouble(),
    );
    final size = terrain['gridSize'] as int;
    final raw = terrain['heights'] as List;
    final grid = TerrainGrid(
      size: size,
      minX: sw.x,
      maxX: ne.x,
      southZ: sw.z,
      northZ: ne.z,
      heights: Float64List.fromList([
        for (final h in raw) (h as num).toDouble() - circuit.meanElevation,
      ]),
      sea: switch (surface?['waterMask']) {
        final List mask when mask.length == size * size => Uint8List.fromList([
          for (final v in mask) (v as num) > 0 ? 1 : 0,
        ]),
        _ => null,
      },
    );

    List<EnvironmentShape> shapes(
      Map<String, dynamic> doc,
      String list,
      String kindKey,
      String pointsKey,
    ) => [
      for (final s
          in (doc[list] as List? ?? const []).cast<Map<String, dynamic>>())
        EnvironmentShape(
          s[kindKey] as String? ?? 'other',
          points(s[pointsKey]),
          height: (s['height'] as num?)?.toDouble() ?? 0,
        ),
    ];

    return CircuitEnvironment(
      terrain: grid,
      water: shapes(water, 'polygons', 'kind', 'points'),
      landuse: shapes(landuse, 'polygons', 'landuse', 'points'),
      roads: shapes(roads, 'roads', 'highway', 'points'),
      buildings: shapes(buildings, 'buildings', 'kind', 'footprint'),
    );
  }

  final TerrainGrid terrain;
  final List<EnvironmentShape> water;
  final List<EnvironmentShape> landuse;
  final List<EnvironmentShape> roads;
  final List<EnvironmentShape> buildings;
}
